
-- local a = function()
    
-- end

-- local function asdf()
    
-- end

-- a = i1
-- return asdf

-- FUNCTION 1: (test)
-- local function test()
--     local a = "test" -- [0]
--     -- CAPTURE 0
--     -- FUNCTION 2: (??)
--     -- NEWCLOURE R0
--     local b= function ()
--         -- GETUPVALUE R1 0
--         -- GETIMPORTED R0 0 [print]
--         print(a)
--         -- RETURN ?
--     end
--     a = 1
--     return b
--     -- RETURN R0
-- end
-- test()()

-- FUNCTION 0: (??)
-- CALL R0
-- RETURN

-- if print("z") == print("z") then
--     print("wow")
-- end


-- while true do
--     print("wow")
--     while true do
--         if print("wow") then break end
--     end
-- end

while true do
end
